# -*- coding: utf-8 -*-
"""Ground-truth pairs for APS-DV-Priyanka.

Source: a 336-page IAS/PCS Mains compilation set in the font. Each raw string
is the stream PyMuPDF extracts; each expected value was read off the rendered
page of that same PDF.
"""

APS_WORDS = [
    ('ØeLece', 'प्रथम'),
    ('efJeÕe', 'विश्व'),
    ('Ùegæ', 'युद्ध'),
    ('kesâ', 'के'),
    ('yeeo', 'बाद'),
    ('cepeotjeW', 'मजदूरों'),
    ('DeeboesueveeW', 'आंदोलनों'),
    ('ceW', 'में'),
    ('DeeÙeer', 'आयी'),
    ('lespeer', 'तेजी'),
    ('keâe', 'का'),
    ('otmeje', 'दूसरा'),
    ('keâejCe', 'कारण'),
    ('YeejleerÙe', 'भारतीय'),
    ('je°^erÙe', 'राष्ट्रीय'),
    ('Deeboesueve', 'आंदोलन'),
    ('ieeBOeerJeeoer', 'गाँधीवादी'),
    ('Ùegie', 'युग'),
    ('Deeieceve', 'आगमन'),
    ('jne~', 'रहा।'),
    ('ieeBOeerpeer', 'गाँधीजी'),
    ('ves', 'ने'),
    ('Deheves', 'अपने'),
    ('DeeOeej', 'आधार'),
    ('keâes', 'को'),
    ('keâjves', 'करने'),
    ('ØeÙelve', 'प्रयत्न'),
    ('efkeâÙee~', 'किया।'),
    ('cepeotj', 'मजदूर'),
    ('Deewj', 'और'),
    ('Ùener', 'यही'),
    ('nw', 'है'),
    ('Éeje', 'द्वारा'),
    ('ieS', 'गए'),
    ('ØecegKe', 'प्रमुख'),
    ('Yeejle', 'भारत'),
    ('keâer', 'की'),
    ('yengle', 'बहुत'),
    ('Lee', 'था'),
    ('efkeâ', 'कि'),
    ('mes', 'से'),
    ('leLee', 'तथा'),
    ('Skeâ', 'एक'),
    ('hej', 'पर'),
    ('Ùen', 'यह'),
    ('nes', 'हो'),
    ('veeje', 'नारा'),
    ('efoÙee', 'दिया'),
    ('nce', 'हम'),
    ('keân', 'कह'),
    ('Øekeâej', 'प्रकार'),
    ('efueS', 'लिए'),
    ('Yeer', 'भी'),
    ('Oegjer', 'धुरी'),
    ('Deesj', 'ओर'),
    ('oyeeJe', 'दबाव'),
    ('mebmeej', 'संसार'),
    ('efceue', 'मिल'),
    ('Yetefcekeâe', 'भूमिका'),

    # Verified in a later pass against the same pages.
    ("meefcceefuele", "सम्मिलित"),
    ("DeJe%ee", "अवज्ञा"),
    ("yecyeF&", "बम्बई"),
    ("keâeheâer", "काफी"),
    ("\u00dfeefcekeâeW", "श्रमिकों"),
    ("Dee\u00a3eve", "आह्वान"),
    ("keâeÙe&keâeefjCeer", "कार्यकारिणी"),
    ("Ûev\u00f5", "चन्द्र"),
    ("efJeÅeeueÙe", "विद्यालय"),
    ("G\u00f2ej", "उत्तर"),
    ("efiejHeäleej", "गिरफ्तार"),
    ("efyeÇefšMe", "ब्रिटिश"),
    ("Ú" "esÌ[es", "छोड़ो"),
]
